- hosts: localhost
  vars:
    github_source_key: "../../../github/.ssh/id_ed25519"
    github_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_github"
    gitlab_source_key: "../../../gitlab/.ssh/id_rsa"
    gitlab_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa_gitlab"
  pre_tasks:
  - name: Update packages
    become: true
    dnf:
      name: '*'
      state: latest
      update_cache: yes
    when: "ansible_os_family == 'RedHat'"
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ssh.yml