- hosts: localhost
  vars:
    # Git
    git_name: "Nikola Lulic"
    # GitHub
    github_git_email: "nlulic@users.noreply.github.com"
    github_source_key: "../../github/.ssh/id_ed25519"
    github_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_github"
    # GitLab
    gitlab_git_email: "2511584-nlulic@users.noreply.gitlab.com"
    gitlab_source_key: "../../gitlab/.ssh/id_rsa"
    gitlab_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa_gitlab"
    # Stow
    stow_dir: "../"
  pre_tasks:
  - name: Update packages
    become: true
    dnf:
      name: '*'
      state: latest
      update_cache: yes
    when: "ansible_os_family == 'RedHat'"
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/git.yml